title = "CTRL config"

[ctrl]
uri = "https://github.com/meop/ctrl"

[ctrl.bak]
provider = "rclone"

[ctrl.dot]
provider = "git"

[ctrl.pkg]
provider = "brew"

[rclone]
uri = "https://downloads.rclone.org/v1.57.0/rclone-v1.57.0-linux-amd64.zip"
