[package]
name = "ctrl"
version = "0.2.0"
edition = "2021"
description = "CLI tool for cross platform OS management"
categories = ["command-line-interface"]

[dependencies]
clap = { version = "^3", features = ["derive"] }
config = { version = "^0" }
serde = { version = "^1", features = ["derive"] }
which = { version = "^4"}

# simple_logger needs this
log = { version = "^0", features = ["std"] }

[dependencies.simple_logger]
default-features = false

# no timestamps for now
features = ["colors"]
version = "^2"
