name: Cargo Release

on:
  push:
    tags: ["v[0-9].[0-9]+.[0-9]+"]

env:
  CARGO_TERM_COLOR: always
  
  # link C runtime statically
  # drop debuginfo and symbols
  RUSTFLAGS: -C target-feature=+crt-static -C split=symbols

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - name: create release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          generate_release_notes: false
    
  build_release:
    needs: create_release
    
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        include:
          - os: macos-latest
            binary: ctrl
            release_binary: ctrl-darwin-aarch64
            release_target: aarch64-apple-darwin
          - os: macos-latest
            binary: ctrl
            release_binary: ctrl-darwin-x86_64
            release_target: x86_64-apple-darwin
          - os: ubuntu-latest
            binary: ctrl
            release_binary: ctrl-linux-aarch64
            release_target: aarch64-unknown-linux-gnu
          - os: ubuntu-latest
            binary: ctrl
            release_binary: ctrl-linux-x86_64
            release_target: x86_64-unknown-linux-gnu
          - os: windows-latest
            binary: ctrl.exe
            release_binary: ctrl-windows-aarch64.exe
            release_target: aarch64-pc-windows-msvc
          - os: windows-latest
            binary: ctrl.exe
            release_binary: ctrl-windows-x86_64.exe
            release_target: x86_64-pc-windows-msvc

    steps:
      - name: checkout
        uses: actions/checkout@v2

      # to get static linking of C/C++ runtime to work
      # you must pass the target as itself
      # https://github.com/rust-lang/rust/issues/78210
      - name: build
        run: cargo build --release --target=${{ matrix.release_target }}

      - name: bundle
        working-directory: target/${{ matrix.release_target }}/release
        run: cp ${{ matrix.binary }} ${{ matrix.release_binary }}

      - name: release
        uses: softprops/action-gh-release@v1
        with:
          # as per getting static linking to work
          # look inside target/ for release/
          # right now, only bundling the binary
          # no config (with defaults), examples, etc
          # inspired by rclone
          files: |
            LICENSE
            target/${{ matrix.release_target }}/release/${{ matrix.release_binary }}
