name: Release

on:
  push:
    tags: ["[0-9].[0-9]+.[0-9]+"]

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          generate_release_notes: false
          prerelease: false
          files: |
            LICENSE

  populate_release:
    runs-on: ${{ matrix.os }}
    needs: create_release

    strategy:
      matrix:
        arch: [aarch64, x86_64]
        os: [macos-latest, ubuntu-latest, windows-latest]
        include:
          - arch: aarch64
            os: macos-latest
            binary: ctrl
            release_binary: ctrl-darwin-aarch64
            release_target: aarch64-apple-darwin
          - arch: x86_64
            os: macos-latest
            binary: ctrl
            release_binary: ctrl-darwin-x86_64
            release_target: x86_64-apple-darwin
          - arch: aarch64
            os: ubuntu-latest
            binary: ctrl
            release_binary: ctrl-linux-aarch64
            release_target: aarch64-unknown-linux-gnu
          - arch: x86_64
            os: ubuntu-latest
            binary: ctrl
            release_binary: ctrl-linux-x86_64
            release_target: x86_64-unknown-linux-gnu
          - arch: aarch64
            os: windows-latest
            binary: ctrl.exe
            release_binary: ctrl-windows-aarch64.exe
            release_target: aarch64-pc-windows-msvc
          - arch: x86_64
            os: windows-latest
            binary: ctrl.exe
            release_binary: ctrl-windows-x86_64.exe
            release_target: x86_64-pc-windows-msvc

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Install GNU GCC for aarch64 [Linux]
        run: sudo apt-get install -y gcc-aarch64-linux-gnu
        if: ${{ matrix.arch == 'aarch64' && matrix.os == 'ubuntu-latest' }}

      - name: Rust target add
        run: rustup target add ${{ matrix.release_target }}

      - name: Cargo build release
        run: cargo build --release --target=${{ matrix.release_target }}

      - name: Copy binary to new name
        run: cp ${{ matrix.binary }} ${{ matrix.release_binary }}
        working-directory: target/${{ matrix.release_target }}/release

      - name: Copy binary into release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/${{ matrix.release_target }}/release/${{ matrix.release_binary }}
